version: '2'

services:
  web:
    build: .
    command: foreman start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - RACK_ENV=development
      - CHURCH_METRICS_USER
      - CHURCH_METRICS_KEY
